
/* eslint-disable */
/**
 * Generated API models.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED.
 */
import { anyApi } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's queries and mutations.
 */
export const api = anyApi as any;
